apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: crunchy-postgres-operator
  namespace: {{ .Release.Namespace }}
spec:
  channel: stable
  installPlanApproval: Automatic
  name: postgresql
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: postgresoperator.{{ .Values.version }}
