global:
  dbClusterName: sso-postgresql
  dbUser: ssouser
  dbPassword: password
  dbName: sso

memoryRequests: 128Mi
memoryLimits: 1Gi
cpuRequests: 100m
cpuLimits: "1"
storageClass: local-sc

backrest:
  publicKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCWE9zMUc2Y1JiZUpGa0xPQStxSXVqOUNtNFdMVVNLV1Z6ZFp3TU5WZVEzQUFBQUpob3RFZWlhTFJICm9nQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQlhPczFHNmNSYmVKRmtMT0ErcUl1ajlDbTRXTFVTS1dWemRad01OVmVRM0EKQUFBRUE4RUxEZHk1NzltRXRMbmNySklyQVlVWG52Z3BPYk9qSHBLb3hRMUx6bHIxYzZ6VWJweEZ0NGtXUXM0RDZvaTZQMApLYmhZdFJJcFpYTjFuQXcxVjVEY0FBQUFEM0poWkhWQWNtUnZiVzUxTFcxaFl3RUNBd1FGQmc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
  privateKey: c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUZjNnpVYnB4RnQ0a1dRczRENm9pNlAwS2JoWXRSSXBaWE4xbkF3MVY1RGMgcmFkdUByZG9tbnUtbWFjCg==
