kind: Secret
apiVersion: v1
metadata:
  name: "{{ .Values.global.dbClusterName }}-primaryuser-secret"
stringData:
  password: "{{ .Values.global.dbPassword }}"
  username: "{{ .Values.global.dbUser }}"
type: Opaque

