{{- if not .Values.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sso.fullname" . }}
stringData:
  dbUser: {{ .Values.db.user }}
  dbPassword: {{ .Values.db.password }}
  ssoUser: {{ .Values.sso.user }}
  ssoPassword: {{ .Values.sso.password }}
  ssoRealm: {{ .Values.sso.realm }}
  ssoServiceUser: {{ .Values.sso.serviceUsername }}
  ssoServicePassword: {{ .Values.sso.servicePassword }}
type: Opaque  
{{- end }}