apiVersion: v1
kind: Service
metadata:
  name: {{ template "sso.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "sso.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ template "sso.fullname" . }}-ssl-certs
spec:
  ports:
    - name: 8443-tcp
      port: 8443
      targetPort: 8443
  selector:
    app.kubernetes.io/name: {{ include "sso.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP